### PR TITLE
Den dev

### PR DESCRIPTION
**Pull request by TartuDen**

### CODE REVIEW

**Comment by TartuDen** [comment]
I added edit/delete buttons. 
I made the pull request, so we can even both branches, i don't like that my branch is getting outdated.
Not solved issue is:
I didn't have time to create any validation for edit/delete, so DO NOT push it ONLINE YET! let's do validation first, if you want i can do it myself tomorrow, or you can take a look.

**Review by Pomog — COMMENTED** [review]
visitor validation absent
______________________________________________

func (m *Repository) EditTopicHandler(w http.ResponseWriter, r *http.Request) {
	if r.Method == http.MethodPost {
	
do we need post method here
______________________________________________________

func (m *Repository) EditTopicResultHandler(w http.ResponseWriter, r *http.Request) {
	if r.Method == http.MethodPost {
	
new post validation absent
__________________________________________________
func (m *Repository) DeleteTopicHandler(w http.ResponseWriter, r *http.Request) {
	if r.Method == http.MethodPost {
		postID, err1 := strconv.Atoi(r.URL.Query().Get("postID"))
		
postID - validation needed
_______________________________
func (m *SqliteBDRepo) EditPost(post models.Post) error {
postID - validation needed

__________________________________
func (m *SqliteBDRepo) DeletePost(post models.Post) error {
postID - validation needed

**Review by Pomog — CHANGES_REQUESTED** [review]
validations should be added

**Comment by TartuDen** [comment]
unc (m *Repository) EditTopicHandler(w http.ResponseWriter, r *http.Request) {
if r.Method == http.MethodPost {

do we need post method here - yes, it does not work without post method

**Pull request closed without merging**
