### PR TITLE
Den dev

### PR DESCRIPTION
**Pull request by TartuDen**

### CODE REVIEW

**Comment by TartuDen** [comment]
the work on last commit is still in progress. Adding buttons to edit delete main topic (thread)

**Review by Pomog — COMMENTED** [review]
m.PostLen
we have AppConfig struct

// Repository handles the repository type, encapsulating the AppConfig and DatabaseInt dependencies.
type Repository struct {
	App *config.AppConfig
	DB  repository.DatabaseInt
}


I an on internal/handler/themeHandler.go now

if len(post.Content) > 1500 { lets aslo store this value in settings, and all value like :1<<20, 2<<20 

```
func AttachFile(w http.ResponseWriter, r *http.Request, post *models.Post, thread *models.Thread) {
	// ADD IMAGE TO STATIC_________________________
	// Get the file from the form data
	file, handler, errFileGet := r.FormFile("image")
	if errFileGet == nil {
		defer file.Close()

		// Validate file size (1 MB limit)
		if handler.Size > 2<<20 {
			setErrorAndRedirect(w, r, "File size should be below 2 MB", "/error-page")
			return
		}
```
post *models.Post, thread *models.Thread - This is strange

1 mb != 2<<20
// Validate file size (1 MB limit)
		if handler.Size > 2<<20 {

 
internal/handler/staticHelperHendlers.go
// Repository handles the repository type, encapsulating the AppConfig and DatabaseInt dependencies.

too many changes - no coments
I an on internal/handler/staticHelperHendlers.go now

**Review by Pomog — CHANGES_REQUESTED** [review]
This branch has conflicts that must be resolved
Use the [web editor](https://github.com/Pomog/ForumFFF/pull/74/conflicts) or the  to resolve conflicts.
Conflicting files
internal/handler/themeHandler.go
internal/repository/sql.go

**Review by Pomog — COMMENTED** [review]
internal/handler/t		

// Validate file size (1 MB limit)
if handler.Size > 2<<20 {hemeHandler.go

// Create a new file in the "static/post_images" directory
newFilePath := filepath.Join("static/post_images", handler.Filename)

this is image for the theme?

 
internal/repository/dbrepo/sqllite.go
```
	if len(post.Content) > 2500 {
		return errors.New("the post is to long, 2500 syblos allowed")
```
previously it was 1500? why here is 2500?


template/home.page.html
did you manage to format the time?



template/theme.page.html
     <label for="image" class="col-form-label">Image: (Max 20 MB), allowed formats jpeg, png, gif.</label>
20 mb is it true?

**Comment by TartuDen** [comment]
did you manage to format the time?
i'm not really sure where and how to do it, can you check and give some suggestions?

**Comment by Pomog** [comment]
image
image
time format example
```
info.Created = thread.Created.Format("2006-01-02 15:04:05")
```

**Comment by TartuDen** [comment]
finished. Description is in commit comment.
issues remained:
1. I could not make so edit/delete button is visible only for creator of post/topic. Due to the way our template is parsed inside the html. Cannot have 2 variables "userIDCreatedPost" and "loggedUserID", to compare them with {{if eq ... }} statement.
2. We discussed - when post is created, by restarting the page we duplicate it. EVERY POST request must be redirected" at the end. This work requires like additional at least one day of work. Can be done during next "dop" for forum.

**Review by Pomog — APPROVED** [review]

**Pull request merged**
